/* eslint-disable no-bitwise -- POSIX file modes are bitfields */
import {afterEach, beforeEach, describe, expect, test, vi} from 'vitest';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {writeMentorshipConfig} from '../../mentorship/config.js';
import {resolveStorageRoots} from '../../storage/paths.js';
import type {StorageRoots} from '../../storage/paths.js';
import {maybeInjectCoaching, run} from '../inject.js';
import {parseActiveAdaptations} from '../profile-reader.js';

type Sandbox = {
  cachePath: string;
  cleanup: () => void;
  homeDirectory: string;
  repoRoot: string;
  roots: StorageRoots;
};

const setupSandbox = (): Sandbox => {
  const repoRoot = mkdtempSync(path.join(tmpdir(), 'gaia-inject-repo-'));
  const homeDirectory = mkdtempSync(path.join(tmpdir(), 'gaia-inject-home-'));
  const roots = resolveStorageRoots({homeDir: homeDirectory, repoRoot});
  // Ensure the `<home>/.claude/projects/<slug>/gaia/` parent exists so we
  // can write a synthetic profile.md without provisioning the full
  // mentorship dir tree (mode-700 ceremony is exercised elsewhere).
  mkdirSync(path.dirname(roots.profilePath), {mode: 0o755, recursive: true});

  return {
    cachePath: path.join(repoRoot, '.gaia', 'cache', 'coaching-active.txt'),
    cleanup: () => {
      rmSync(repoRoot, {force: true, recursive: true});
      rmSync(homeDirectory, {force: true, recursive: true});
    },
    homeDirectory,
    repoRoot,
    roots,
  };
};

const enableMentorship = (roots: StorageRoots): void => {
  writeMentorshipConfig({
    analyticsEnabled: true,
    decidedVia: 'gaia-init',
    enabled: true,
    roots,
  });
};

const writeProfile = (profilePath: string, body: string): void => {
  writeFileSync(profilePath, body, {mode: 0o600});
};

const ACTIVE_PROFILE = `> DO NOT EDIT: regenerated by \`gaia telemetry compute-profile\`. Use \`gaia mentorship purge\` or \`disable\` to change state.

# Mentorship profile

Generated: 2026-05-07T12:34:56.789Z
Window: last 30 days
Mentorship enabled: true

## Active patterns

- articulation_gap (visual): strength 0.62, samples 33

## Active adaptations

- po_socratic_depth_increased - area: visual, strength: 0.62, samples: 33

## Faded adaptations

(none)

## Pattern detail
`;

const EMPTY_PROFILE = `> DO NOT EDIT: regenerated by \`gaia telemetry compute-profile\`. Use \`gaia mentorship purge\` or \`disable\` to change state.

# Mentorship profile

Generated: 2026-05-07T12:34:56.789Z
Window: last 30 days
Mentorship enabled: true

## Active patterns

(none, all patterns below sample threshold or strength below threshold)

## Active adaptations

(none)

## Faded adaptations

(none)

## Pattern detail
`;

describe('adaptation/profile-reader', () => {
  test('parses an active adaptation row with `area: <tag>` syntax', () => {
    const result = parseActiveAdaptations(ACTIVE_PROFILE);

    expect(result).toEqual([
      {adaptation_id: 'po_socratic_depth_increased', area_tag: 'visual'},
    ]);
  });

  test('returns [] when the section body reads "(none)"', () => {
    expect(parseActiveAdaptations(EMPTY_PROFILE)).toEqual([]);
  });

  test('returns [] when the section is absent', () => {
    expect(
      parseActiveAdaptations('# Some other doc\n\nno section here.')
    ).toEqual([]);
  });

  test('stops at the next ## heading (does not bleed into Faded)', () => {
    const profile = `## Active adaptations

- po_socratic_depth_increased - area: visual

## Faded adaptations

- engineer_commentary_verbosity_increased - area: react
`;
    const result = parseActiveAdaptations(profile);

    expect(result).toEqual([
      {adaptation_id: 'po_socratic_depth_increased', area_tag: 'visual'},
    ]);
  });

  test('ignores bullets that do not match a known adaptation id', () => {
    const profile = `## Active adaptations

- some_unknown_adaptation - area: visual
- po_socratic_depth_increased - area: react
`;
    const result = parseActiveAdaptations(profile);

    expect(result).toEqual([
      {adaptation_id: 'po_socratic_depth_increased', area_tag: 'react'},
    ]);
  });

  test('parses multiple active adaptations in order', () => {
    const profile = `## Active adaptations

- po_socratic_depth_increased - area: visual, strength: 0.6
- engineer_commentary_verbosity_increased - area: react, strength: 0.55
- po_example_specs_offered - area: form, strength: 0.51

## Faded adaptations
`;
    const result = parseActiveAdaptations(profile);

    expect(result).toEqual([
      {adaptation_id: 'po_socratic_depth_increased', area_tag: 'visual'},
      {
        adaptation_id: 'engineer_commentary_verbosity_increased',
        area_tag: 'react',
      },
      {adaptation_id: 'po_example_specs_offered', area_tag: 'form'},
    ]);
  });
});

describe('adaptation/inject: maybeInjectCoaching', () => {
  let sandbox: Sandbox;

  beforeEach(() => {
    sandbox = setupSandbox();
  });

  afterEach(() => {
    sandbox.cleanup();
  });

  test('UAT-034: returns "" when mentorship is disabled (byte-identical path)', async () => {
    writeMentorshipConfig({
      analyticsEnabled: false,
      decidedVia: 'gaia-init',
      enabled: false,
      roots: sandbox.roots,
    });
    writeProfile(sandbox.roots.profilePath, ACTIVE_PROFILE);

    const result = await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['visual']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toBe('');
    expect(existsSync(sandbox.cachePath)).toBe(false);
  });

  test('UAT-034: returns "" when profile.md is absent', async () => {
    enableMentorship(sandbox.roots);

    const result = await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['visual']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toBe('');
    expect(existsSync(sandbox.cachePath)).toBe(false);
  });

  test('UAT-034: returns "" when profile.md has no active adaptations', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(sandbox.roots.profilePath, EMPTY_PROFILE);

    const result = await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['visual']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toBe('');
    expect(existsSync(sandbox.cachePath)).toBe(false);
  });

  test('UAT-034: returns "" when no active adaptation matches the requested area', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(sandbox.roots.profilePath, ACTIVE_PROFILE);

    const result = await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['form']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toBe('');
    expect(existsSync(sandbox.cachePath)).toBe(false);
  });

  test('UAT-033: returns coaching block with {{area}} substituted', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(sandbox.roots.profilePath, ACTIVE_PROFILE);

    const result = await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['visual']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toContain('## Profile-driven coaching');
    expect(result).toContain('articulating success criteria for visual work');
    expect(result).not.toContain('{{area}}');
  });

  test('UAT-033/037: writes cache file with content "1" mode 644 on non-empty injection', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(sandbox.roots.profilePath, ACTIVE_PROFILE);

    await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['visual']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(existsSync(sandbox.cachePath)).toBe(true);
    expect(readFileSync(sandbox.cachePath, 'utf8')).toBe('1');
    expect(statSync(sandbox.cachePath).mode & 0o777).toBe(0o644);
  });

  test('cache write is idempotent: repeated invocations do not error', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(sandbox.roots.profilePath, ACTIVE_PROFILE);

    await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['visual']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );
    await maybeInjectCoaching(
      {agentType: 'PO', areaTags: ['visual']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(readFileSync(sandbox.cachePath, 'utf8')).toBe('1');
  });

  test('areaTags absent → falls back to first active adaptation', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(sandbox.roots.profilePath, ACTIVE_PROFILE);

    const result = await maybeInjectCoaching(
      {agentType: 'PO'},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toContain('articulating success criteria for visual work');
  });

  test('areaTags empty array → falls back to first active adaptation', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(sandbox.roots.profilePath, ACTIVE_PROFILE);

    const result = await maybeInjectCoaching(
      {agentType: 'PO', areaTags: []},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toContain('articulating success criteria for visual work');
  });

  test('multiple adaptations: first matching area wins', async () => {
    enableMentorship(sandbox.roots);
    writeProfile(
      sandbox.roots.profilePath,
      `## Active adaptations

- po_socratic_depth_increased - area: visual
- engineer_commentary_verbosity_increased - area: react

## Faded adaptations
`
    );

    const result = await maybeInjectCoaching(
      {agentType: 'Senior', areaTags: ['react']},
      {cachePath: sandbox.cachePath, roots: sandbox.roots}
    );

    expect(result).toContain('codebase orientation when working in react');
  });
});

describe('adaptation/inject: _internal-fetch-coaching CLI handler', () => {
  let sandbox: Sandbox;
  let stdoutSpy: ReturnType<typeof vi.spyOn>;
  let stderrSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    sandbox = setupSandbox();
    // Suppress stdout/stderr writes during these tests; the `run`
    // handler's CLI-shaped output would otherwise leak into the test
    // reporter.
    stdoutSpy = vi.spyOn(process.stdout, 'write').mockReturnValue(true);
    stderrSpy = vi.spyOn(process.stderr, 'write').mockReturnValue(true);
  });

  afterEach(() => {
    stdoutSpy.mockRestore();
    stderrSpy.mockRestore();
    sandbox.cleanup();
  });

  test('rejects missing --agent-type with non-zero exit', async () => {
    const code = await run(['--area-tags', 'visual']);

    expect(code).not.toBe(0);
  });

  test('rejects unknown --agent-type value with non-zero exit', async () => {
    const code = await run(['--agent-type', 'NotAnAgent']);

    expect(code).not.toBe(0);
  });

  test('exits 0 with a valid --agent-type (empty string output is the v1.0.0 default)', async () => {
    // The handler resolves real repo storage roots; in CI the repo's
    // mentorship is disabled by default, so the printed result is "";
    // which is exactly the byte-identical UAT-034 path. We assert only
    // the exit code; the empty stdout is what the bash caller's
    // `COACHING=$(...)` capture relies on.
    const code = await run(['--agent-type', 'PO', '--area-tags', 'visual']);

    expect(code).toBe(0);
  });
});
