/**
 * profile.md DO-NOT-EDIT header content.
 *
 * The exact wording is contract: tests verify the regenerated file's
 * top-of-file header reads exactly this string.
 */
export const PROFILE_DO_NOT_EDIT_HEADER =
  '> DO NOT EDIT — regenerated by `gaia telemetry compute-profile`. Use `gaia mentorship purge` or `disable` to change state.';
