/**
 * profile.md DO-NOT-EDIT header content (UAT-036).
 *
 * The exact wording is contract: UAT-036 verifies the regenerated file's
 * top-of-file header reads exactly this string. Changing it requires a
 * SPEC amendment.
 */
export const PROFILE_DO_NOT_EDIT_HEADER =
  '> DO NOT EDIT — regenerated by `gaia telemetry compute-profile`. Use `gaia mentorship purge` or `disable` to change state.';
